# Generated by Django 3.1.4 on 2020-12-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('web', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('employees_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_2l', models.CharField(max_length=2)),
                ('code_3l', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
            ],
            options={
                'verbose_name_plural': 'Tickers',
            },
        ),
    ]
