# Generated by Django 3.1.4 on 2020-12-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_2l', models.CharField(max_length=2)),
                ('code_3l', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_abbr', models.CharField(max_length=4)),
                ('web', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('employees_count', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.country')),
            ],
        ),
    ]
